name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:

    strategy:
      matrix:
        platform: [
          'linux-arm',
          'linux-arm64',
          'linux-x64',
          'darwin-x64',
        ]

        include:
          - platform: 'linux-arm'
            host-os: 'ubuntu-latest'
          - platform: 'linux-arm64'
            host-os: 'ubuntu-latest'
          - platform: 'linux-x64'
            host-os: 'ubuntu-latest'
          - platform: 'darwin-x64'
            host-os: 'macos-latest'

    runs-on: ${{ matrix.host-os }}

    steps:
    - uses: actions/checkout@v1
    - name: Build adapter
      run: |
        ./build.sh "${{ matrix.platform }}"
